name: safaqtek
description: Safaqtek is an e-commerce application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 2.2.0
  cupertino_icons: ^1.0.2
  intl_utils: ^2.6.1
  intl: ^0.17.0
  percent_indicator: ^4.0.0
  chips_choice_null_safety: ^2.0.4
  device_preview: ^1.0.0
  intl_phone_field: ^3.0.0
  regexpattern: ^2.0.1
  rounded_loading_button: ^2.1.0
  another_flushbar: ^1.10.28
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  otp_text_field: ^1.1.2
  firebase_auth_web: ^3.3.9
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  modal_bottom_sheet: ^2.0.1
  dio: ^4.0.4
  connectivity_plus: ^2.2.1
  provider: ^6.0.2
  google_sign_in: ^5.2.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  sign_in_with_apple: ^3.3.0
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  flutter_credit_card: ^3.0.1
  credit_card_validator: ^2.0.1
  google_maps_flutter: ^2.1.3
  permission_handler: ^9.2.0
  location: ^4.3.0
  image_picker: ^0.8.5
  country_list_pick: ^1.0.1+5
  youtube_player_flutter: ^8.0.0
  youtube_video_info: ^1.0.1
  shimmer: ^2.0.0
  shimmer_animation: ^2.1.0+1
  youtube_explode_dart: ^1.10.10+2
  shared_preferences: ^2.0.13
  flutter_phone_direct_caller: ^2.1.0
  carousel_slider: ^4.1.1
  get_it: ^7.2.0
  firebase_dynamic_links: ^4.2.2
  share_plus: ^4.0.4
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^2.5.0
  url_launcher: ^6.1.2
  flutter_email_sender: ^5.1.0
  pull_to_refresh: ^2.0.0
  cloud_functions: ^3.2.15
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/countriesFlags/

  fonts:
    - family: CairoSemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.TTF
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.TTF


flutter_intl:
  enabled: true